try:
    print(a + b)
except exception as e:
    print(e)
    